---
booktitle: 'Proceedings of the 4th International Workshop on Big Data, Streams and
  Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications'
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
volume: 41
year: '2015'
shortname: BigMine
start: 2015-08-10
end: 2015-08-10
published: 2015-08-31
sections:
- name: front
  title: Front Matter
- name: demo
  title: Invited Demo Talks
- name: default
  title: Accepted Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: BIGMINE-2015
month: 0
cycles: false
editor:
- given: Wei
  family: Fan
- given: Albert
  family: Bifet
- given: Qiang
  family: Yang
- given: Philip S.
  family: Yu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 4th International Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms, Systems, Programming Models and Applications on 10 August 2015

  Published as Volume 41 by the Proceedings of Machine Learning Research on 31 August 2015.

  Volume Edited by:
    Wei Fan
    Albert Bifet
    Qiang Yang
    Philip S. Yu

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 10 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v41"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
permalink: "/:title.html"
ghub:
  edit: true
  repository: v41
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: 'Workshop on Big Data, Streams and Heterogeneous Source Mining: Algorithms,
    Systems, Programming Models and Applications'
  url: http://bigdata-mining.org/bigmine-15/
  location: 
  dates:
  - 2015-08-10
  number: 4
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
